"""Realtime financial-news monitoring backed by NewsNow."""

from .newsnow import (
    DEFAULT_ENDPOINT,
    DEFAULT_MAX_IMPORTANT_ITEMS,
    DEFAULT_MAX_ITEMS,
    DEFAULT_SOURCE_IDS,
    MAX_MAX_IMPORTANT_ITEMS,
    MAX_MAX_ITEMS,
    MIN_MAX_IMPORTANT_ITEMS,
    MIN_MAX_ITEMS,
    NEWSNOW_SOURCE_REGISTRY_REVISION,
    NewsNowClient,
    NewsNowConfig,
    NewsNowConfigurationError,
    NewsNowError,
    NewsNowRequestError,
    NewsNowResponseError,
    NewsNowService,
    SUPPORTED_SOURCES,
    normalize_endpoint,
    parse_source_ids,
    shared_newsnow_service,
    source_options,
)

__all__ = [
    "DEFAULT_ENDPOINT",
    "DEFAULT_MAX_IMPORTANT_ITEMS",
    "DEFAULT_MAX_ITEMS",
    "DEFAULT_SOURCE_IDS",
    "MAX_MAX_IMPORTANT_ITEMS",
    "MAX_MAX_ITEMS",
    "MIN_MAX_IMPORTANT_ITEMS",
    "MIN_MAX_ITEMS",
    "NEWSNOW_SOURCE_REGISTRY_REVISION",
    "NewsNowClient",
    "NewsNowConfig",
    "NewsNowConfigurationError",
    "NewsNowError",
    "NewsNowRequestError",
    "NewsNowResponseError",
    "NewsNowService",
    "SUPPORTED_SOURCES",
    "normalize_endpoint",
    "parse_source_ids",
    "shared_newsnow_service",
    "source_options",
]
